# Generated by Django 5.0.1 on 2024-03-28 12:44

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_orderdetail_total_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Customer", "verbose_name_plural": "Customers"},
        ),
        migrations.AlterModelOptions(
            name="orderdetail",
            options={
                "verbose_name": "Order Detail",
                "verbose_name_plural": "Order Details",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="area",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("product"), "+", models.F("order")
                ),
                output_field=models.CharField(),
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderdetail",
            unique_together={("product", "order")},
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customer_info",
        ),
    ]
