# Generated by Django 5.0.1 on 2024-03-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_customer_options_alter_orderdetail_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdetail",
            name="area",
        ),
    ]
