# Generated by Django 5.0.1 on 2024-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_loggingrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggingrecord",
            name="path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="loggingrecord",
            name="status_code",
            field=models.IntegerField(null=True),
        ),
    ]
